### ISSUE TITLE
problems in streaming process

### ISSUE THREAD

**Issue by PokerN** [anders-dc/lbm-d3q19#1]
Hi, I downloaded your code, and learned a lot of skill from your code. 
However, I also found that there is something wired in the streaming process.
So, I write this test file. 
The method used is map the distribution function location to a real number in order to
look what happened after streaming process.
The result is :##########################################
7.00    7.10    7.20    7.30    7.40  
  7.01    7.11    7.21    7.31    7.41  
  7.02    7.12    7.22    7.32    7.42  
  7.03    7.13    7.23    7.33    7.43  
  7.04    7.14    7.24    7.34    7.44  
RESULT: Direction 7-----------------------
XY PLANE: 
  8.00    0.00    0.00    0.00    10.41  
  9.00    7.00    7.10    7.20    10.42  
  9.01    7.01    7.11    7.21    10.43  
  9.02    7.02    7.12    7.22    10.44  
  9.03    7.03    7.13    7.23    7.33  
RESULT: Direction 18------------------------
YZ PLANE: 
  14.00    14.10    14.20    14.30    14.40  
  18.00    18.10    18.20    18.30    18.40  
  18.01    18.11    18.21    18.31    18.41  
  18.02    18.12    18.22    18.32    18.42  
  18.03    18.13    18.23    18.33    18.43  
###### 

So, that is incorrect.
I have pull the test file to your repository.
Thanks for your sharing with my best wishes.

**Comment by anders-dc** [comment]
Thanks for chiming in!  I will take a look at it.

**Comment by anders-dc** [comment]
Could you please make a pull request with the test file?

**Comment by anders-dc** [comment]
Resolved in fc71734e79e62bc8bb6d94c90a2dc9f8e28b892d
